### ISSUE TITLE
Order of indices

### ISSUE THREAD

**Issue by emanjavacas** [stephantul/reach#4]
I could look it up myself, but since I am lazy:
If I load the vectors passing `wordlist`, is it guaranteed that `r.vectors` entries will be in the same order?
Basically, what I need is the embedding matrix and a vector of words (strings) in correspondence with the words in the matrix (without having to sort again).

Also, the package in pip seems to be outdated :-p

**Comment by stephantul** [comment]
Hey,

I think the answer to your question is yes. `reach` requires that your `wordlist` and `vectors` are aligned when you initialize them. Since `reach` has no way of knowing what vectors actually correspond to, it is assumed that word `N` will always correspond to vector `N`. 

There is only a weak guarantee that the internal indices in `reach` will be sorted, as we use dictionaries for indexing. Dictionaries are only guaranteed to retain order in python 3.6+. We don't keep the original list or array. 

So what I would propose is that you initialize an instance with your word list + vectors, and then convert the word list to an array and keep this array external. This would allow you to use `reach` for whatever you like, while still having an external reference to use. 

I know the package on pip is outdated.

**Comment by emanjavacas** [comment]
But there will be mismatches if there is no vector for a given input word, right?
